---
title: "xFpts_no_min_requirement"
author: "Christopher Adams"
date: "8/9/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)
```

## Data setup

```{r set_options}
wd = "~/Documents/GitHub/overthinking_football/fantrax_scripts"
min_starts_requirement <- 5
## JUST MAKE SURE NOT A SUB
```

```{r data_setup}
#load all player data for fbref.com
setwd(wd)
weekly_data_csv = "../data/fantrax_data/weekly.all_data_combined.no_double_gws.updated_positions.csv"

weekly_data_df <- read_csv(file = weekly_data_csv, col_names = TRUE)

# Only weeks where at least 60 minutes are played
min_minute_df <- weekly_data_df[weekly_data_df$SubOn == 0 & weekly_data_df$GP == 1,]
# Players that have started at least 5 games
summary_min_minutes_df <- min_minute_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min), sd = sd(FPts), mean = mean(FPts), total_fpts = sum(FPts), mean_minutes = mean(Min))

#only players with at least 5 starts
players_min_starts_summary_df <- summary_min_minutes_df[summary_min_minutes_df$n >= min_starts_requirement,]

player_min_starts_weekly_df <- min_minute_df %>%
  filter(Player %in% players_min_starts_summary_df$Player)
nrow(player_min_starts_weekly_df)


```

## get xFpts

```{r gather_xfpt_df}

#negate %in%
`%!in%` = Negate(`%in%`)

#### Standard calculations for all players ####

#read in fbref_summary data
fbref_summ_df <- read_csv('../data/fbref/premier_league/19_20/name_cleaned.summary_table.game_week.csv')

#clean sheet data
cs_df <- read_csv('../data/fantrax_data/game_results.csv')
#just get the important stuff for clean sheets (name "Team.y" for easy merge in a sec)
all_cs_data_df <- data.frame('Team.y' = c(cs_df$Home, cs_df$Away), 'xG_against' = c(cs_df$xG_1, cs_df$xG), 'game_week' = c(cs_df$Wk, cs_df$Wk))
# add fbref data
min_minutes_weekly_merged_df <- merge(player_min_starts_weekly_df, fbref_summ_df, by=c('Player', 'game_week'))
# add clean sheet data
min_minutes_merged_cs_df <- merge(min_minutes_weekly_merged_df, all_cs_data_df, by=c("Team.y", "game_week"))
# calculate xGAD and xCS
min_minutes_merged_cs_df$xGAD <- ifelse(min_minutes_merged_cs_df$xG_against - 0.25 < 0, 0, min_minutes_merged_cs_df$xG_against - 0.25)
min_minutes_merged_cs_df$xCS <- ifelse(min_minutes_merged_cs_df$xGAD <= 1.25, 1 - min_minutes_merged_cs_df$xGAD/1.25, 0)
filtered_weekly_player_df <- min_minutes_merged_cs_df

#### DEFENDERS xFPTS ####
#calculate xFpts for defenders
def.filtered_weekly_player_df <- filtered_weekly_player_df[filtered_weekly_player_df$Position == 'D',]
# calculate fpts based on the updated fantrax rules
def.filtered_weekly_player_df$updated_fpts <- def.filtered_weekly_player_df$G * 10 +
  def.filtered_weekly_player_df$AT * 7 +
  def.filtered_weekly_player_df$KP * 2 +
  def.filtered_weekly_player_df$SOT * 2 +
  def.filtered_weekly_player_df$ACNC * 1 +
  def.filtered_weekly_player_df$CoS * 1 +
  def.filtered_weekly_player_df$TkW * 1 +
  def.filtered_weekly_player_df$Int.x * 1 +
  def.filtered_weekly_player_df$AER * 1 +
  def.filtered_weekly_player_df$CLR * 0.25 +
  def.filtered_weekly_player_df$DIS * -0.5 +
  def.filtered_weekly_player_df$PKM * -4 +
  def.filtered_weekly_player_df$OG * -5 +
  def.filtered_weekly_player_df$YC * -3 +
  def.filtered_weekly_player_df$RC * -7 +
  def.filtered_weekly_player_df$CS * 6 +
  def.filtered_weekly_player_df$GAD * -2 +
  def.filtered_weekly_player_df$CoS * 1

def.filtered_weekly_player_df$xFpts <- def.filtered_weekly_player_df$xG * 10 +
  def.filtered_weekly_player_df$xA * 7 +
  def.filtered_weekly_player_df$KP * 2 +
  def.filtered_weekly_player_df$SOT * 2 +
  def.filtered_weekly_player_df$ACNC * 1 +
  def.filtered_weekly_player_df$CoS * 1 +
  def.filtered_weekly_player_df$TkW * 1 +
  def.filtered_weekly_player_df$Int.x * 1 +
  def.filtered_weekly_player_df$AER * 1 +
  def.filtered_weekly_player_df$CLR * 0.25 +
  def.filtered_weekly_player_df$DIS * -0.5 +
  def.filtered_weekly_player_df$PKM * -4 +
  def.filtered_weekly_player_df$OG * -5 +
  def.filtered_weekly_player_df$YC * -3 +
  def.filtered_weekly_player_df$RC * -7 +
  def.filtered_weekly_player_df$xCS * 6 +
  def.filtered_weekly_player_df$xGAD * -2 +
  def.filtered_weekly_player_df$CoS * 1

#### MIDFIELDERS xFPTS ####

#load in just midfielders
mid.filtered_weekly_player_df = filtered_weekly_player_df[filtered_weekly_player_df$Position == 'M',]

# calculate fpts based on the updated fantrax rules
mid.filtered_weekly_player_df$updated_fpts <- mid.filtered_weekly_player_df$G * 9 +
  mid.filtered_weekly_player_df$AT * 6 +
  mid.filtered_weekly_player_df$KP * 2 +
  mid.filtered_weekly_player_df$SOT * 2 +
  mid.filtered_weekly_player_df$ACNC * 1 +
  mid.filtered_weekly_player_df$CoS * 1 +
  mid.filtered_weekly_player_df$TkW * 1 +
  mid.filtered_weekly_player_df$Int.x * 1 +
  mid.filtered_weekly_player_df$AER * 0.5 +
  mid.filtered_weekly_player_df$CLR * 0 +
  mid.filtered_weekly_player_df$DIS * -0.5 +
  mid.filtered_weekly_player_df$PKM * -4 +
  mid.filtered_weekly_player_df$OG * -5 +
  mid.filtered_weekly_player_df$YC * -3 +
  mid.filtered_weekly_player_df$RC * -7 +
  mid.filtered_weekly_player_df$CS * 1 +
  mid.filtered_weekly_player_df$GAD * 0 +
  mid.filtered_weekly_player_df$CoS * 1

#calculate xFpts for midfielders
mid.filtered_weekly_player_df$xFpts <- mid.filtered_weekly_player_df$xG * 9 +
  mid.filtered_weekly_player_df$xA * 6 +
  mid.filtered_weekly_player_df$KP * 2 +
  mid.filtered_weekly_player_df$SOT * 2 +
  mid.filtered_weekly_player_df$ACNC * 1 +
  mid.filtered_weekly_player_df$CoS * 1 +
  mid.filtered_weekly_player_df$TkW * 1 +
  mid.filtered_weekly_player_df$Int.x * 1 +
  mid.filtered_weekly_player_df$AER * 0.5 +
  mid.filtered_weekly_player_df$CLR * 0 +
  mid.filtered_weekly_player_df$DIS * -0.5 +
  mid.filtered_weekly_player_df$PKM * -4 +
  mid.filtered_weekly_player_df$OG * -5 +
  mid.filtered_weekly_player_df$YC * -3 +
  mid.filtered_weekly_player_df$RC * -7 +
  mid.filtered_weekly_player_df$xCS * 1 +
  mid.filtered_weekly_player_df$GAD * 0 +
  mid.filtered_weekly_player_df$CoS * 1


#### FORWARDS xFPTS ####

#load in just forwards
for.filtered_weekly_player_df = filtered_weekly_player_df[filtered_weekly_player_df$Position == 'F',]

# calculate fpts based on the updated fantrax rules
for.filtered_weekly_player_df$updated_fpts <- for.filtered_weekly_player_df$G * 9 +
  for.filtered_weekly_player_df$AT * 6 +
  for.filtered_weekly_player_df$KP * 2 +
  for.filtered_weekly_player_df$SOT * 2 +
  for.filtered_weekly_player_df$ACNC * 1 +
  for.filtered_weekly_player_df$CoS * 1 +
  for.filtered_weekly_player_df$TkW * 1 +
  for.filtered_weekly_player_df$Int.x * 1 +
  for.filtered_weekly_player_df$AER * 0.5 +
  for.filtered_weekly_player_df$CLR * 0 +
  for.filtered_weekly_player_df$DIS * -0.5 +
  for.filtered_weekly_player_df$PKM * -4 +
  for.filtered_weekly_player_df$OG * -5 +
  for.filtered_weekly_player_df$YC * -3 +
  for.filtered_weekly_player_df$RC * -7 +
  for.filtered_weekly_player_df$CS * 0 +
  for.filtered_weekly_player_df$GAD * 0 +
  for.filtered_weekly_player_df$CoS * 1

#calculate xFpts for midfielders
for.filtered_weekly_player_df$xFpts <- for.filtered_weekly_player_df$xG * 9 +
  for.filtered_weekly_player_df$xA * 6 +
  for.filtered_weekly_player_df$KP * 2 +
  for.filtered_weekly_player_df$SOT * 2 +
  for.filtered_weekly_player_df$ACNC * 1 +
  for.filtered_weekly_player_df$CoS * 1 +
  for.filtered_weekly_player_df$TkW * 1 +
  for.filtered_weekly_player_df$Int.x * 1 +
  for.filtered_weekly_player_df$AER * 0.5 +
  for.filtered_weekly_player_df$CLR * 0 +
  for.filtered_weekly_player_df$DIS * -0.5 +
  for.filtered_weekly_player_df$PKM * -4 +
  for.filtered_weekly_player_df$OG * -5 +
  for.filtered_weekly_player_df$YC * -3 +
  for.filtered_weekly_player_df$RC * -7 +
  for.filtered_weekly_player_df$xCS * 0 +
  for.filtered_weekly_player_df$GAD * 0 +
  for.filtered_weekly_player_df$CoS * 1

#combine all the position dataframes into one
all_combined_df <- rbind(def.filtered_weekly_player_df, mid.filtered_weekly_player_df, for.filtered_weekly_player_df)
write.csv(x = all_combined_df, file = "../data/fantrax_data/weekly_data.no_min_requirement.updated_positions.xFpts_epl_2019_2020.csv")

summary_combined_xfpts_df <- all_combined_df %>% 
  group_by(Player, Team.x, Position) %>%
  summarize(n = n(), min_total = sum(Min.x),  mean_minutes = mean(Min.x), mean_xFpts = mean(xFpts), sd_xFpts = sd(xFpts), median_xFpts = median(xFpts), mean_fpts = mean(updated_fpts), sd_fpts = sd(updated_fpts), median_ftps = median(updated_fpts),  total_xFpts = sum(xFpts), total_fpts = sum(updated_fpts), mean_xCS = mean(xCS), xCS = sum(xCS), CS = sum(CS))

hist(summary_combined_xfpts_df$sd_xFpts)
hist(summary_combined_xfpts_df$sd_fpts)
write.csv(x = summary_combined_xfpts_df, file = "../data/fantrax_data/no_min_requirement.updated_positions.xFpts_epl_2019_2020.csv")
```