---
title: "xFpts"
author: "Christopher Adams"
date: "6/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)
```

## Data setup

```{r set_options}

min_starts_requirement <- 5
min_minutes_requirement <- 60
```

```{r data_setup}
#load all player data for fbref.com
weekly_data_csv = "../data/fantrax_data/weekly.all_data_combined.no_double_gws.csv"
yearly_data_csv = "../data/fantrax_data/yearly.all_data_combined.csv"

weekly_data_df <- read_csv(file = weekly_data_csv, col_names = TRUE)
yearly_data_df <- read_csv(file = yearly_data_csv, col_names = TRUE)

# Only weeks where at least 60 minutes are played
min_minute_df <- weekly_data_df[weekly_data_df$Min >= min_minutes_requirement,]
# Players that have started at least 5 games
summary_min_minutes_df <- min_minute_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min), sd = sd(FPts), mean = mean(FPts), total_fpts = sum(FPts), mean_minutes = mean(Min))

#only players with at least 5 starts
players_min_starts_summary_df <- summary_min_minutes_df[summary_min_minutes_df$n >= min_starts_requirement,]

player_min_starts_weekly_df <- min_minute_df %>%
  filter(Player %in% players_min_starts_summary_df$Player)
nrow(player_min_starts_weekly_df)


```

## get xFpts

```{r gather_xfpt_df}

#### DEFENDERS xFPTS ####

# load in just defenders
players_min_starts.defenders = players_min_starts_summary_df[players_min_starts_summary_df$Position == 'D',]
nrow(players_min_starts.defenders)
def_player_list <- players_min_starts.defenders$Player
length(def_player_list)

#read in fbref_summary data
fbref_summ_df <- read_csv('../data/fbref/premier_league/19_20/name_cleaned.summary_table.first_360_matches_game_week.csv')

dim(fbref_summ_df)

#clean sheet data
cs_df <- read_csv('../data/fantrax_data/game_results.csv')

#merge on player and game week
min_minutes_weekly_merged_df <- merge(min_minute_df, fbref_summ_df, by=c('Player', 'game_week'))


#filter on fantrax defenders
defenders_min_minutes_merged_df <- min_minutes_weekly_merged_df[min_minutes_weekly_merged_df$Position == "D",]

sum(def_player_list %in% unique(defenders_min_minutes_merged_df$Player))
#[1] 138
#so they are all there

#negate %in%
`%!in%` = Negate(`%in%`)

#see which players are extra in this group
Players_defenders_min_minutes_merged_df<-unique(defenders_min_minutes_merged_df$Player)

Players_defenders_min_minutes_merged_df[Players_defenders_min_minutes_merged_df %!in% def_player_list]

#they are players who havent have 5 starts

#remove the under 5 games players
defenders_min_minutes_merged_df <- defenders_min_minutes_merged_df[defenders_min_minutes_merged_df$Player %in% def_player_list,]

dim(defenders_min_minutes_merged_df)
#[1] 2715  125

#just get the important stuff for clean sheets (name "Team.y" for easy merge in a sec)
all_cs_data_df <- data.frame('Team.y' = c(cs_df$Home, cs_df$Away), 'xG_against' = c(cs_df$xG_1, cs_df$xG), 'game_week' = c(cs_df$Wk, cs_df$Wk))

#convert squad to character all_cs_data_df for merge
all_cs_data_df$Team.y <- as.character(all_cs_data_df$Team.y)

#merge cs and defender data
defenders_min_minutes_merged_cs_df <- merge(defenders_min_minutes_merged_df, all_cs_data_df, by=c("Team.y", "game_week"))

dim(defenders_min_minutes_merged_cs_df)
#[1] 2715  126

#calculate xFpts from cs given xG against
defenders_min_minutes_merged_cs_df$GAD_against <- ifelse(defenders_min_minutes_merged_cs_df$xG_against - 0.25 < 0, 0, defenders_min_minutes_merged_cs_df$xG_against - 0.25)

defenders_min_minutes_merged_cs_df$normed_xg_against <- ifelse(defenders_min_minutes_merged_cs_df$GAD_against <= 1.25, 1 - defenders_min_minutes_merged_cs_df$GAD_against/1.25, 0)

#calculate xFpts for defenders
defenders_min_minutes_merged_cs_df$xPts <- defenders_min_minutes_merged_cs_df$FPts - (defenders_min_minutes_merged_cs_df$G * 10 + defenders_min_minutes_merged_cs_df$AT * 8 + defenders_min_minutes_merged_cs_df$CS * 6 + defenders_min_minutes_merged_cs_df$GAD * -2) + (as.numeric(defenders_min_minutes_merged_cs_df$xG)* 10 + as.numeric(defenders_min_minutes_merged_cs_df$xA) * 8 + as.numeric(defenders_min_minutes_merged_cs_df$normed_xg_against)* 6 + as.numeric(defenders_min_minutes_merged_cs_df$GAD_against) * -2)

#remove some extra defender columns
drops <- c("normed_xg_against","GAD_against", 'xG_against')
defenders_min_minutes_merged_cs_df <- defenders_min_minutes_merged_cs_df[ , !(names(defenders_min_minutes_merged_cs_df) %in% drops)]

#### MIDFIELDERS xFPTS ####

#load in just midfielders
players_min_starts.midfielders = players_min_starts_summary_df[players_min_starts_summary_df$Position == 'M',]
nrow(players_min_starts.midfielders)
mid_player_list <- players_min_starts.midfielders$Player

length(mid_player_list)

#filter on fantrax midfielders
mids_min_minutes_merged_df <- min_minutes_weekly_merged_df[min_minutes_weekly_merged_df$Position == "M",]

length(unique(mids_min_minutes_merged_df$Player))


sum(mid_player_list %in% unique(mids_min_minutes_merged_df$Player))

#remove the under 5 games players
mids_min_minutes_merged_df <- mids_min_minutes_merged_df[mids_min_minutes_merged_df$Player %in% mid_player_list,]

dim(mids_min_minutes_merged_df)
#[1] 2600  125


length(unique(mids_min_minutes_merged_df$Player))
#[1] 143

#calculate xFpts for midfielders
mids_min_minutes_merged_df$xPts <- mids_min_minutes_merged_df$FPts - (mids_min_minutes_merged_df$G * 9 + mids_min_minutes_merged_df$AT * 6)
mids_min_minutes_merged_df$xPts <- mids_min_minutes_merged_df$xPts + (as.numeric(mids_min_minutes_merged_df$xG)* 9 + as.numeric(mids_min_minutes_merged_df$xA) * 6)

#### FORWARDS xFPTS ####

#load in just forwards
players_min_starts.forwards = players_min_starts_summary_df[players_min_starts_summary_df$Position == 'F',]
nrow(players_min_starts.forwards)

for_player_list <- players_min_starts.forwards$Player

length(for_player_list)
#[1] 71


#filter on fantrax forwards
fwds_min_minutes_merged_df <- min_minutes_weekly_merged_df[min_minutes_weekly_merged_df$Position == "F",]

length(unique(fwds_min_minutes_merged_df$Player))
#[1] 81

sum(for_player_list %in% unique(fwds_min_minutes_merged_df$Player))

#remove the under min games players
fwds_min_minutes_merged_df <- fwds_min_minutes_merged_df[fwds_min_minutes_merged_df$Player %in% for_player_list,]

dim(fwds_min_minutes_merged_df)

length(unique(fwds_min_minutes_merged_df$Player))

#calculate xFpts for forwards
fwds_min_minutes_merged_df$xPts <- fwds_min_minutes_merged_df$FPts - (fwds_min_minutes_merged_df$G * 9 + fwds_min_minutes_merged_df$AT * 6)
fwds_min_minutes_merged_df$xPts <- fwds_min_minutes_merged_df$xPts + (as.numeric(fwds_min_minutes_merged_df$xG)* 9 + as.numeric(fwds_min_minutes_merged_df$xA) * 6)


#combine all the position dataframes into one
all_combined_df <- rbind(defenders_min_minutes_merged_cs_df, fwds_min_minutes_merged_df, mids_min_minutes_merged_df)
```

