---
title: "Pos_v_team_xfpts"
author: "Christopher Adams"
date: "6/26/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)

library(RColorBrewer)
team_colors <- c(
          '#c8102E',
          '#6CABDD',
          '#003090',
          '#034694',
          '#DA291C',
          '#FDB913',
          "#132257",
          "#ee2737",
          "#EF0107",
          "#1B458F",
          "#6C1D45",
          "#003399",
          "white",
          "#d71920",
          "#0057B8",
          "#FBEE23",
          "#7A263A",
          "#DA291C",
          "#670e36",
          "#00A650")
teams = c('Liverpool',
          'Manchester City',
          'Leicester City',
          'Chelsea',
          'Manchester Utd',
          'Wolves',
          "Tottenham",
          "Sheffield Utd",
          "Arsenal",
          "Crystal Palace",
          "Burnley",
          "Everton",
          "Newcastle Utd",
          "Southampton",
          "Brighton",
          "Watford",
          "West Ham",
          "Bournemouth",
          "Aston Villa",
          "Norwich City")
names(team_colors) <- teams
colScale <- scale_colour_manual(name = "opposition",values = team_colors)
fillScale <- scale_fill_manual(name = "opposition",values = team_colors, guide = FALSE)
```

## Data setup

```{r data_setup}

weekly_data_csv = "~/Documents/GitHub/soccer_analytics/data/fantrax_data/weekly.all_data_combined.no_double_gws.csv"
yearly_data_csv = "~/Documents/GitHub/soccer_analytics/data/fantrax_data/yearly.all_data_combined.csv"

weekly_data_df <- read_csv(file = weekly_data_csv, col_names = TRUE)
yearly_data_df <- read_csv(file = yearly_data_csv, col_names = TRUE)

# Only weeks where at least 60 minutes are played
min_60_min_df <- weekly_data_df[weekly_data_df$Min > 59,]
# Players that have started at least 5 games
summary_min_60_df <- min_60_min_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min), sd = sd(FPts), mean = mean(FPts), total_fpts = sum(FPts), mean_minutes = mean(Min))
min_25_p_owned <- yearly_data_df[as.numeric(sub("%", "", yearly_data_df$`% Owned`)) >= 25,]$Player
players_min_5_starts_summary_df <- summary_min_60_df[summary_min_60_df$n >= 5,] #%>%
  #filter(Player %in% min_25_p_owned)

player_min_5_starts_weekly_df <- min_60_min_df %>%
  filter(Player %in% players_min_5_starts_summary_df$Player) %>%
  filter(Player %in% min_25_p_owned)
nrow(player_min_5_starts_weekly_df)
```

## Defender Analysis



```{r defender_scatter_analysis}
players_min_starts.defenders = players_min_5_starts_summary_df[players_min_5_starts_summary_df$Position == 'D',]
nrow(players_min_starts.defenders)

def_player_list <- players_min_starts.defenders$Player
length(def_player_list)
defenders_fbref_df <- read_csv('~/Desktop/Overthinking_Football/player_fbref_match_csvs/Def_min5starts.csv')
cs_df <- read_csv('~/Desktop/Overthinking_Football/player_fbref_match_csvs/game_results.csv')
defenders_fbref_df$game_week <- sapply(strsplit(defenders_fbref_df$Round, " "), function(x) (x[2]))
defenders_min60_merged_df <- merge(min_60_min_df, defenders_fbref_df, by=c('Player', 'game_week'))
length(unique(defenders_min60_merged_df$Player))
i <- def_player_list %in% unique(defenders_min60_merged_df$Player)
def_player_list[!i]
all_cs_data_df <- data.frame('Squad' = c(cs_df$Home, cs_df$Away), 'xG_against' = c(cs_df$xG_1, cs_df$xG), 'game_week' = c(cs_df$Wk, cs_df$Wk))

defenders_min60_merged_cs_df <- merge(defenders_min60_merged_df, all_cs_data_df, by=c('Squad', 'game_week'))

defenders_min60_merged_cs_df$GAD_against <- ifelse(defenders_min60_merged_cs_df$xG_against - 0.25 < 0, 0, defenders_min60_merged_cs_df$xG_against - 0.25)

defenders_min60_merged_cs_df$normed_xg_against <- ifelse(defenders_min60_merged_cs_df$GAD_against <= 1.25, 1 - defenders_min60_merged_cs_df$GAD_against/1.25, 0)

per90_ratio <- 90 / defenders_min60_merged_cs_df$Min.x
defenders_min60_merged_cs_df$xg_against_scaled_p90 <- defenders_min60_merged_cs_df$xG_against * per90_ratio


defenders_min60_min600_merged_df <- defenders_min60_merged_cs_df %>%
  filter(Player %in% def_player_list)

defenders_min60_min600_merged_df$xPts <- defenders_min60_min600_merged_df$FPts - (defenders_min60_min600_merged_df$G * 10 + defenders_min60_min600_merged_df$AT * 8 + defenders_min60_min600_merged_df$CS * 6 + defenders_min60_min600_merged_df$GAD * -2) + (as.numeric(defenders_min60_min600_merged_df$xG)* 10 + as.numeric(defenders_min60_min600_merged_df$xA) * 8 + as.numeric(defenders_min60_min600_merged_df$normed_xg_against)* 6 + as.numeric(defenders_min60_min600_merged_df$GAD_against) * -2)

defenders_min60_min600_merged_df$GAD_against_p90 <- ifelse(defenders_min60_min600_merged_df$xg_against_scaled_p90 - 0.25 < 0, 0, defenders_min60_min600_merged_df$xg_against_scaled_p90 - 0.25)

defenders_min60_min600_merged_df$normed_xg_against_p90 <- ifelse(defenders_min60_min600_merged_df$GAD_against_p90 <= 1.25, 1 - defenders_min60_min600_merged_df$GAD_against_p90/1.25, 0)

defenders_min60_min600_merged_df$xPts_p90 <- defenders_min60_min600_merged_df$FPts * per90_ratio  - (defenders_min60_min600_merged_df$G * 10 + defenders_min60_min600_merged_df$AT * 8 + defenders_min60_min600_merged_df$CS * 6 + defenders_min60_min600_merged_df$GAD * -2) + ((as.numeric(defenders_min60_min600_merged_df$xG)* 10 + as.numeric(defenders_min60_min600_merged_df$xA) * 8) * per90_ratio + as.numeric(defenders_min60_min600_merged_df$normed_xg_against_p90)* 6 + as.numeric(defenders_min60_min600_merged_df$GAD_against_p90) * -2)



summary_xpts_df.def <- defenders_min60_min600_merged_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min.x), sd_emp_pts = sd(FPts), sd_xpts = sd(xPts), mean_emp_pts = mean(FPts), mean_xPts = mean(xPts), med_emp_pts= median(FPts), med_xPts = median(xPts), total_emp_fpts = sum(FPts), total_xPts = sum(xPts), mean_minutes = mean(Min.x), n_CS = sum(CS), xCS = sum(normed_xg_against), sd_p_90 = sd(xPts_p90), mean_p90 = mean(xPts_p90))

diff_df <- merge(defenders_min60_min600_merged_df, summary_xpts_df.def, by = c('Player'))
diff_df$mean_dev <- diff_df$xPts - diff_df$mean_xPts
diff_df$rel_dev <- (diff_df$xPts - diff_df$mean_xPts) / diff_df$sd_xpts

diff_df$dev_p90 <- (diff_df$xPts_p90 - diff_df$mean_p90) / diff_df$sd_p_90
#wilcox.test(x = diff_df[diff_df$opposition == 'Manchester City', 'rel_dev'], y = diff_df[diff_df$opposition == 'Liverpool', 'rel_dev'])
summary_per_team <- diff_df %>% 
  group_by(Opponent.y) %>%
  summarize(n = n(), sd_xpts = sd(mean_dev), mean_xPts = mean(mean_dev), med = median(mean_dev), rel_dev_median = median(rel_dev), p90_med = median(dev_p90))

diff_df$opposition <- factor(diff_df$Opponent.y,
                             levels = c('Liverpool',
                                        'Manchester City',
                                        'Leicester City',
                                        'Chelsea',
                                        'Manchester Utd',
                                        'Wolves',
                                        "Tottenham",
                                        "Sheffield Utd",
                                        "Arsenal",
                                        "Crystal Palace",
                                        "Burnley",
                                        "Everton",
                                        "Newcastle Utd",
                                        "Southampton",
                                        "Brighton",
                                        "Watford",
                                        "West Ham",
                                        "Bournemouth",
                                        "Aston Villa",
                                        "Norwich City"))
diff_df$opposition <- factor(diff_df$Opponent.y, levels = as.vector(summary_per_team[order(summary_per_team$rel_dev_median), ]$Opponent.y))
ggplot(data = diff_df, aes(x=opposition, y = rel_dev, fill = opposition)) +
  geom_boxplot(aes()) +
  geom_hline(yintercept = 0) +
    theme_light(base_size = 18) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Standard deviations from average xFpts performance") +
  xlab("Opposing team") +
  ggtitle("Defender xFpt performance against different opposition") +
  theme(plot.title = element_text(hjust = 0.5)) +
  colScale +
  fillScale
ggsave(filename = "~/Desktop/Overthinking_Football/Team_pos_plots/Defender_xFpt_per_position.png", width = 14, height = 8)

diff_df$opposition <- factor(diff_df$Opponent.y, levels = as.vector(summary_per_team[order(summary_per_team$p90_med), ]$Opponent.y))
ggplot(data = diff_df, aes(x=opposition, y = dev_p90, fill = opposition)) +
  geom_boxplot(aes()) +
  geom_hline(yintercept = 0) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Standard deviations from average xFpts performance") +
  xlab("Opposing team") +
  ggtitle("Defender xFpt performance against different opposition") +
  theme(plot.title = element_text(hjust = 0.5)) +
  colScale +
  fillScale


```

## Midfielder Analysis

```{r midfielder_scatter_analysis}
players_min_starts.midfielders = players_min_5_starts_summary_df[players_min_5_starts_summary_df$Position == 'M',]
nrow(players_min_starts.midfielders)
mid_player_list <- players_min_starts.midfielders$Player

mids_fbref_df <- read_csv('~/Desktop/Overthinking_Football/player_fbref_match_csvs/Mid_min5starts.csv')
mids_fbref_df$game_week <- sapply(strsplit(mids_fbref_df$Round, " "), function(x) (x[2]))
mids_min60_merged_df <- merge(min_60_min_df, mids_fbref_df, by=c('Player', 'game_week'))

i <- mid_player_list %in% unique(mids_min60_merged_df$Player)
mid_player_list[!i]

mids_min60_min600_merged_df <- mids_min60_merged_df %>%
  filter(Player %in% mid_player_list)

mids_min60_min600_merged_df$xPts <- mids_min60_min600_merged_df$FPts - (mids_min60_min600_merged_df$G * 9 + mids_min60_min600_merged_df$AT * 6)
mids_min60_min600_merged_df$xPts <- mids_min60_min600_merged_df$xPts + (as.numeric(mids_min60_min600_merged_df$xG)* 9 + as.numeric(mids_min60_min600_merged_df$xA) * 6)

#mids_min60_min600_merged_df_after_jan <- mids_min60_min600_merged_df[mids_min60_min600_merged_df$game_week > 21,]
mids_min60_min600_merged_df$xPts_p90 <- mids_min60_min600_merged_df$xPts / mids_min60_min600_merged_df$Min.x * 90
summary_xpts_df.mid <- mids_min60_min600_merged_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min.x), sd_emp_pts = sd(FPts), sd_xpts = sd(xPts), mean_emp_pts = mean(FPts), mean_xPts = mean(xPts), med_emp_pts= median(FPts), med_xPts = median(xPts), total_emp_fpts = sum(FPts), total_xPts = sum(xPts), mean_minutes = mean(Min.x), sd_p_90 = sd(xPts_p90), mean_p90 = mean(xPts_p90))

diff_df <- merge(mids_min60_min600_merged_df, summary_xpts_df.mid, by = c('Player'))


diff_df$mean_dev <- diff_df$xPts - diff_df$mean_xPts
diff_df$rel_dev <- (diff_df$xPts - diff_df$mean_xPts) / diff_df$sd_xpts
diff_df$dev_p90 <- (diff_df$xPts_p90 - diff_df$mean_p90) / diff_df$sd_p_90
summary_per_team <- diff_df %>% 
  group_by(Opponent.y) %>%
  summarize(n = n(), sd_xpts = sd(mean_dev), mean_xPts = mean(mean_dev), med = median(mean_dev), p90_med = median(dev_p90), rel_dev_med = median(rel_dev))

diff_df$opposition <- factor(diff_df$Opponent.y,
                             levels = c('Liverpool',
                                        'Manchester City',
                                        'Leicester City',
                                        'Chelsea',
                                        'Manchester Utd',
                                        'Wolves',
                                        "Tottenham",
                                        "Sheffield Utd",
                                        "Arsenal",
                                        "Crystal Palace",
                                        "Burnley",
                                        "Everton",
                                        "Newcastle Utd",
                                        "Southampton",
                                        "Brighton",
                                        "Watford",
                                        "West Ham",
                                        "Bournemouth",
                                        "Aston Villa",
                                        "Norwich City"))

diff_df$opposition <- factor(diff_df$Opponent.y, levels = as.vector(summary_per_team[order(summary_per_team$rel_dev_med), ]$Opponent.y))
ggplot(data = diff_df, aes(x=opposition, y =rel_dev, fill = opposition)) +
  geom_boxplot()  +
  geom_hline(yintercept = 0) +
  theme_light(base_size = 18) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Standard deviations from average xFpts performance") +
  xlab("Opposing team") +
  ggtitle("Midfielder performance against different opposition") +
  theme(plot.title = element_text(hjust = 0.5)) +
  colScale +
  fillScale

ggsave(filename = "~/Desktop/Overthinking_Football/Team_pos_plots/Midfielder_xFpt_per_position.png", width = 14, height = 8)
diff_df$opposition <- factor(diff_df$Opponent.y, levels = as.vector(summary_per_team[order(summary_per_team$p90_med), ]$Opponent.y))
ggplot(data = diff_df, aes(x=opposition, y =dev_p90, fill = opposition)) +
  geom_boxplot()  +
  geom_hline(yintercept = 0) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("xFpts deviation from mean score") +
  ggtitle("Midfielder performance against different opposition") +
  theme(plot.title = element_text(hjust = 0.5)) +
  colScale +
  fillScale
```


## Forwards Analysis


```{r forward_analysis}
players_min_starts.forwards = players_min_5_starts_summary_df[players_min_5_starts_summary_df$Position == 'F',]
nrow(players_min_starts.forwards)
for_player_list <- players_min_starts.forwards$Player

fwds_fbref_df <- read_csv('~/Desktop/Overthinking_Football/player_fbref_match_csvs/For_min5starts.csv')
fwds_fbref_df$game_week <- sapply(strsplit(fwds_fbref_df$Round, " "), function(x) (x[2]))
fwds_min60_merged_df <- merge(min_60_min_df, fwds_fbref_df, by=c('Player', 'game_week'))

i <- for_player_list %in% unique(fwds_min60_merged_df$Player)
for_player_list[!i]

fwds_min60_min600_merged_df <- fwds_min60_merged_df %>%
  filter(Player %in% for_player_list)

fwds_min60_min600_merged_df$xPts <- fwds_min60_min600_merged_df$FPts - (fwds_min60_min600_merged_df$G * 9 + fwds_min60_min600_merged_df$AT * 6)
fwds_min60_min600_merged_df$xPts <- fwds_min60_min600_merged_df$xPts + (as.numeric(fwds_min60_min600_merged_df$xG)* 9 + as.numeric(fwds_min60_min600_merged_df$xA) * 6)

summary_xpts_df.for <- fwds_min60_min600_merged_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min.x), sd_emp_pts = sd(FPts), sd_xpts = sd(xPts), mean_emp_pts = mean(FPts), mean_xPts = mean(xPts), med_emp_pts= median(FPts), med_xPts = median(xPts), total_emp_fpts = sum(FPts), total_xPts = sum(xPts), mean_minutes = mean(Min.x))

diff_df <- merge(fwds_min60_min600_merged_df, summary_xpts_df.for, by = c('Player'))
diff_df$mean_dev <- diff_df$xPts - diff_df$mean_xPts
diff_df$rel_dev <- (diff_df$xPts - diff_df$mean_xPts) / diff_df$sd_xpts

summary_per_team <- diff_df %>% 
  group_by(Opponent.y) %>%
  summarize(n = n(), sd_xpts = sd(mean_dev), mean_xPts = mean(mean_dev), med = median(mean_dev), rel_med = median(rel_dev))

diff_df$opposition <- factor(diff_df$Opponent.y,
                             levels = c('Liverpool',
                                        'Manchester City',
                                        'Leicester City',
                                        'Chelsea',
                                        'Manchester Utd',
                                        'Wolves',
                                        "Tottenham",
                                        "Sheffield Utd",
                                        "Arsenal",
                                        "Crystal Palace",
                                        "Burnley",
                                        "Everton",
                                        "Newcastle Utd",
                                        "Southampton",
                                        "Brighton",
                                        "Watford",
                                        "West Ham",
                                        "Bournemouth",
                                        "Aston Villa",
                                        "Norwich City"))
diff_df$opposition <- factor(diff_df$Opponent.y, levels = as.vector(summary_per_team[order(summary_per_team$rel_med), ]$Opponent.y))
ggplot(data = diff_df, aes(x=opposition, y = rel_dev, fill = opposition)) +
  geom_boxplot()  +
  geom_hline(yintercept = 0) +
  theme_light(base_size = 18) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("Standard deviations from average xFpts performance") +
  xlab("Opposing team") +
  ggtitle("Forward performance against different opposition") +
  theme(plot.title = element_text(hjust = 0.5)) +
  colScale +
  fillScale

ggsave(filename = "~/Desktop/Overthinking_Football/Team_pos_plots/Forward_xFpt_per_position.png", width = 14, height = 8)
```





### AERIALS

```{r defender_scatter_analysis}
players_min_starts.defenders = players_min_5_starts_summary_df[players_min_5_starts_summary_df$Position == 'D',]
nrow(players_min_starts.defenders)

def_player_list <- players_min_starts.defenders$Player
length(def_player_list)
defenders_fbref_df <- read_csv('~/Desktop/Overthinking_Football/player_fbref_match_csvs/Def_min5starts.csv')
cs_df <- read_csv('~/Desktop/Overthinking_Football/player_fbref_match_csvs/game_results.csv')
defenders_fbref_df$game_week <- sapply(strsplit(defenders_fbref_df$Round, " "), function(x) (x[2]))
defenders_min60_merged_df <- merge(min_60_min_df, defenders_fbref_df, by=c('Player', 'game_week'))
length(unique(defenders_min60_merged_df$Player))
i <- def_player_list %in% unique(defenders_min60_merged_df$Player)
def_player_list[!i]
all_cs_data_df <- data.frame('Squad' = c(cs_df$Home, cs_df$Away), 'xG_against' = c(cs_df$xG_1, cs_df$xG), 'game_week' = c(cs_df$Wk, cs_df$Wk))

defenders_min60_merged_cs_df <- merge(defenders_min60_merged_df, all_cs_data_df, by=c('Squad', 'game_week'))

defenders_min60_merged_cs_df$GAD_against <- ifelse(defenders_min60_merged_cs_df$xG_against - 0.25 < 0, 0, defenders_min60_merged_cs_df$xG_against - 0.25)

defenders_min60_merged_cs_df$normed_xg_against <- ifelse(defenders_min60_merged_cs_df$GAD_against <= 1.25, 1 - defenders_min60_merged_cs_df$GAD_against/1.25, 0)

defenders_min60_min600_merged_df <- defenders_min60_merged_cs_df %>%
  filter(Player %in% def_player_list)

defenders_min60_min600_merged_df$xPts <- defenders_min60_min600_merged_df$FPts - (defenders_min60_min600_merged_df$G * 10 + defenders_min60_min600_merged_df$AT * 8 + defenders_min60_min600_merged_df$CS * 6 + defenders_min60_min600_merged_df$GAD * -2) + (as.numeric(defenders_min60_min600_merged_df$xG)* 10 + as.numeric(defenders_min60_min600_merged_df$xA) * 8 + as.numeric(defenders_min60_min600_merged_df$normed_xg_against)* 6 + as.numeric(defenders_min60_min600_merged_df$GAD_against) * -2)




summary_xpts_df.def <- defenders_min60_min600_merged_df %>% 
  group_by(Player, Team, Position) %>%
  summarize(n = n(), min_total = sum(Min.x), sd_emp_pts = sd(FPts), sd_xpts = sd(xPts), mean_emp_pts = mean(FPts), mean_xPts = mean(xPts), med_emp_pts= median(FPts), med_xPts = median(xPts), total_emp_fpts = sum(FPts), total_xPts = sum(xPts), mean_minutes = mean(Min.x), n_CS = sum(CS), xCS = sum(normed_xg_against), mean_aerial = mean(KP))

diff_df <- merge(defenders_min60_min600_merged_df, summary_xpts_df.def, by = c('Player'))
diff_df$mean_dev <- diff_df$xPts - diff_df$mean_xPts
diff_df$rel_dev <- (diff_df$xPts - diff_df$mean_xPts) / diff_df$sd_xpts

summary_per_team <- diff_df %>% 
  group_by(Opponent.y) %>%
  summarize(n = n(), sd_xpts = sd(mean_dev), mean_xPts = mean(mean_dev), med = median(mean_dev))

diff_df$opposition <- factor(diff_df$Opponent.y,
                             levels = c('Liverpool',
                                        'Manchester City',
                                        'Leicester City',
                                        'Chelsea',
                                        'Manchester Utd',
                                        'Wolves',
                                        "Tottenham",
                                        "Sheffield Utd",
                                        "Arsenal",
                                        "Crystal Palace",
                                        "Burnley",
                                        "Everton",
                                        "Newcastle Utd",
                                        "Southampton",
                                        "Brighton",
                                        "Watford",
                                        "West Ham",
                                        "Bournemouth",
                                        "Aston Villa",
                                        "Norwich City"))
diff_df$opposition <- factor(diff_df$Opponent.y, levels = as.vector(summary_per_team[order(summary_per_team$med), ]$Opponent.y))
ggplot(data = diff_df, aes(x=opposition, y = rel_dev, fill = opposition)) +
  geom_boxplot() +
  geom_hline(yintercept = 0) +
  theme_light() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ylab("xFpts deviation from mean score") +
  ggtitle("Defender performance against different opposition") +
  theme(plot.title = element_text(hjust = 0.5)) +
  colScale +
  fillScale

```
